import { Link } from 'react-router-dom'
import styles from './Legal.module.css'

export default function Terms() {
  return (
    <div className={styles.page}>
      <div className={styles.container}>
        <Link to="/" className={styles.back}>← Back to Precision Training</Link>
        <h1>Terms of Use & Medical Disclaimer</h1>
        <p className={styles.updated}>Last updated: April 2026</p>

        {/* Medical disclaimer — most important, first */}
        <div style={{
          padding: '20px 24px', borderRadius: 12, marginBottom: 32,
          background: 'rgba(220,80,80,0.06)', border: '1px solid rgba(220,80,80,0.2)',
        }}>
          <h2 style={{ color: '#e06060', marginTop: 0 }}>⚠ Medical Disclaimer — Please Read</h2>
          <p>Precision Training provides AI-generated fitness and nutrition plans for <strong>informational and educational purposes only</strong>. The content generated by this service does <strong>not</strong> constitute medical advice, diagnosis, or treatment.</p>
          <p>Precision Training is <strong>not a licensed medical provider, registered dietitian, or certified physician</strong>. No content on this platform should be interpreted as professional medical or nutritional guidance.</p>
          <p><strong>GLP-1 Medication Users:</strong> If you are taking or considering GLP-1 medications (including but not limited to Ozempic, Wegovy, Mounjaro, or Zepbound), you <strong>must consult your prescribing physician or a qualified healthcare professional</strong> before starting any new exercise or nutrition program. The GLP-1 Muscle Guard plans are designed as general fitness frameworks and are not a substitute for personalized medical supervision.</p>
          <p><strong>Always consult a qualified healthcare professional before:</strong></p>
          <ul>
            <li>Starting a new exercise program, especially if you have pre-existing conditions</li>
            <li>Making significant changes to your diet or caloric intake</li>
            <li>Adjusting or starting any medication, including GLP-1 agonists</li>
            <li>Exercising after illness, surgery, or injury</li>
          </ul>
          <p style={{ marginBottom: 0 }}>If you experience chest pain, shortness of breath, dizziness, nausea, or any unusual symptoms during exercise, <strong>stop immediately and seek medical attention</strong>.</p>
        </div>

        <h2>1. Acceptance of Terms</h2>
        <p>By accessing or using Precision Training ("the Service") at precision-training.io, you agree to be bound by these Terms of Use. If you do not agree with any part of these terms, you must not use the Service.</p>

        <h2>2. Nature of the Service</h2>
        <p>Precision Training is a software platform that uses artificial intelligence to generate personalized fitness and nutrition plans based on user-provided data. The plans are generated algorithmically and are intended as general wellness frameworks only. They are not clinical prescriptions and do not replace the judgment of qualified fitness professionals, physicians, or registered dietitians.</p>

        <h2>3. No Medical Advice</h2>
        <p>Nothing on this platform constitutes medical advice. The information provided — including training plans, nutrition plans, macro calculations, supplement suggestions, and GLP-1 related content — is for general informational purposes only. Precision Training expressly disclaims any responsibility for any adverse effects arising directly or indirectly from use of this information.</p>

        <h2>4. User Responsibility</h2>
        <p>You are solely responsible for how you use the plans and information provided. You acknowledge that:</p>
        <ul>
          <li>You are in adequate physical health to participate in the exercise programs described</li>
          <li>You will seek medical clearance if you have any doubts about your health status</li>
          <li>You will not use these plans as a replacement for professional medical or nutritional advice</li>
          <li>You assume all risk of injury or adverse health outcomes arising from your use of these plans</li>
        </ul>

        <h2>5. Accuracy of AI-Generated Content</h2>
        <p>Plans are generated by artificial intelligence models and may contain errors, inaccuracies, or information that is not suitable for your individual circumstances. Precision Training does not guarantee the accuracy, completeness, or suitability of any generated content. Always apply common sense and consult a professional when in doubt.</p>

        <h2>6. GLP-1 Specific Disclaimer</h2>
        <p>The GLP-1 Muscle Guard plans are designed as general fitness and nutrition frameworks for individuals who report using GLP-1 receptor agonist medications. These plans are based on publicly available research regarding resistance training and protein intake during caloric restriction. They are not designed, reviewed, or approved by medical professionals and should not replace individualized medical advice from your prescribing physician or healthcare team.</p>
        <p>Medication dosing, scheduling, and potential drug interactions are entirely outside the scope of this Service. Any questions related to your medication should be directed exclusively to your healthcare provider.</p>

        <h2>7. Supplement Recommendations</h2>
        <p>Any supplement suggestions in generated plans (including creatine, protein powders, vitamins, or minerals) are general recommendations only. Consult a healthcare professional before starting any supplement regimen, particularly if you are taking prescription medications.</p>

        <h2>8. Limitation of Liability</h2>
        <p>To the maximum extent permitted by applicable law, Precision Training, its owner, operators, and affiliates shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to personal injury, health complications, or financial loss.</p>

        <h2>9. Intellectual Property</h2>
        <p>The software, design, and methodology of Precision Training are proprietary. Your generated plan is for your personal use only and may not be redistributed, resold, or published without written permission.</p>

        <h2>10. Changes to Terms</h2>
        <p>We reserve the right to update these Terms at any time. Continued use of the Service after changes are posted constitutes acceptance of the revised Terms.</p>

        <h2>11. Governing Law</h2>
        <p>These Terms are governed by the laws of the Federal Republic of Germany. Any disputes shall be subject to the jurisdiction of the courts of Munich, Germany.</p>

        <h2>12. Contact</h2>
        <p>
          Precision Training<br />
          Florian Rappold<br />
          Maikäferstraße 3f, 85551 Kirchheim, Germany<br />
          Email: <a href="mailto:info@precision-training.io">info@precision-training.io</a>
        </p>
      </div>
    </div>
  )
}
